{% set version = "2.5.2" %}

package:
  name: livereload
  version: {{ version }}

source:
  fn: livereload-{{ version }}.tar.gz
  url: https://github.com/lepture/python-livereload/archive/v{{ version }}.tar.gz
  sha256: f4a7bb0ad818b9d9c61fbc96692fe2a23a401b36a062b77bd8e23d0c4274e3a6

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - livereload = livereload.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado
    - six

test:
  imports:
    - livereload
  commands:
    - livereload --help

about:
  home: https://github.com/lepture/python-livereload
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python LiveReload is an awesome tool for web developers.'

extra:
  recipe-maintainers:
    - ocefpaf
