{% set version = "2.5.0" %}

package:
  name: livereload
  version: {{ version }}

source:
  fn: livereload-{{ version }}.tar.gz
  url: https://github.com/lepture/python-livereload/archive/v{{ version }}.tar.gz
  sha256: 79eca97371dd7d565f81372889f27d4f71a5efaba7f973e7e160c5556ee86be8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - livereload = livereload.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - tornado
    - six

test:
  imports:
    - livereload
  commands:
    - livereload --help

about:
  home: https://github.com/lepture/python-livereload
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python LiveReload is an awesome tool for web developers.'

extra:
  recipe-maintainers:
    - ocefpaf
