{% set version = "2.5.1" %}

package:
  name: livereload
  version: {{ version }}

source:
  fn: livereload-{{ version }}.tar.gz
  url: https://github.com/lepture/python-livereload/archive/v{{ version }}.tar.gz
  sha256: b90a47fb761a6c4a770454ccf1cf03d0351a415ff04bf87bc8a531f945cbc8ab

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - livereload = livereload.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - tornado
    - six

test:
  imports:
    - livereload
  commands:
    - livereload --help

about:
  home: https://github.com/lepture/python-livereload
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python LiveReload is an awesome tool for web developers.'

extra:
  recipe-maintainers:
    - ocefpaf
