{% set version = "2.6.0" %}

package:
  name: livereload
  version: {{ version }}

source:
  url: https://github.com/lepture/python-livereload/archive/v{{ version }}.tar.gz
  sha256: 98e914a211016967e3d53517b78d683e0e513e2fe0974e4a9a7066328cddc045

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - livereload = livereload.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado
    - six

test:
  imports:
    - livereload
  commands:
    - livereload --help

about:
  home: https://github.com/lepture/python-livereload
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python LiveReload is an awesome tool for web developers.'

extra:
  recipe-maintainers:
    - ocefpaf
