{% set version = "2.6.2" %}

package:
  name: livereload
  version: {{ version }}

source:
  url: https://github.com/lepture/python-livereload/archive/{{ version }}.tar.gz
  sha256: 52cf71161c17fb0afa9dad321f64975388bff1797baee61162887eb07aec427e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - livereload = livereload.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado
    - six

test:
  imports:
    - livereload
  commands:
    - pip check
    - livereload --help
  requires:
    - pip

about:
  home: https://github.com/lepture/python-livereload
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python LiveReload is an awesome tool for web developers

extra:
  recipe-maintainers:
    - ocefpaf
