{% set version = "2.6.1" %}

package:
  name: livereload
  version: {{ version }}

source:
  url: https://github.com/lepture/python-livereload/archive/v{{ version }}.tar.gz
  sha256: f432db9266f80a2a30144cdf1ea4d3c6f39ebf58a636fd64c4e8dc18c601ffaf

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - livereload = livereload.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado
    - six

test:
  imports:
    - livereload
  commands:
    - livereload --help

about:
  home: https://github.com/lepture/python-livereload
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Python LiveReload is an awesome tool for web developers'

extra:
  recipe-maintainers:
    - ocefpaf
