travis:
  secure:
    BINSTAR_TOKEN: iQzk3HHUgwuBkNfa2jdROhj22IpEaVruaDtuEWKgfTcEGayLEgKvTcWkOiwVCtiGvql+MVyqbhYTGLVz1bAtXb0Tu31GZTu6WOjp4Q410Gra5rW8m9MyCgVlCmSgTZOuJw9MSg3ePGx0DoZNZv+p9k8yh2K7NQW42rclu/Zr686mM0IvhHnwMCj/6uJgBVFaV3cySSM9FeNOgCH6PrZQ8ryFP2noftDcDZh7xLVvyrEUaRE39jBLYI887PZnwUpSjx3oQLb1ev0l4FsKxz7iDJHfU7CoJVp5ZZ52U2wVXnYH0dXBiU4Nb38gAhjhrZZAt5rb2d+fbpG8wyRTMuqkaZkX0dMBiQWMSyVVhlW0kSbdmVPntOGhqvi09Gi9ufAC6ixISDielAQzR1QdWSk3Ng13rHYzY+iTDPD5L+HQgETgAUkt4xCenXbV12UNkWLauphdtkrWdVuxT6gGG5h3d6j7ocxlZKsHKyepNwwk6j/RUZW6o0qF99iXzHKMH/BcY5JxKppR12kbUN+d0XJ6aRQa7q9W6PHtiTU7mRTKk5Dv0lAvLmBp2fBCz83F4VVAv7IlbNSu8Oe1BPJjCVAvMXkyLQ2iuTXai3Peqxj3Yf8OVUYWGnsQunz8z7xq3W+JlsM+CxzbV+Jl3CTzMDotQIKPLyY4dRcyhW/Qq/H9oEg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
