travis:
  secure:
    BINSTAR_TOKEN: fogrmTSKJk8nrYy5eYPNIhkLkbISCuCdY3fTCBJmEaCrAX9vxOgMyzTjm5J7ikz/FomgcbEfRSmnC0+ZnWxEkyYNgnj9asjD/OTZasVxwChP+6vX2JMXuNIooA6D3Eo6IYdzfPOElXh3sW5ZFXgf/1phAzEexd4xNqQRweawE+A4G4DeDaEegBxv/enqWjA31mFiFsY8Q7JzXx2FcYIwLRjqVQN/g7JtHIoktODpsLYIqIb6nheBgmR6I00qcq+qmcEbfWdS0h3RWW9Kweq+UB7NjWcS7uTSGPKuxVroXtZr0A9zPeDlui5hvO3qRMPQPWandHDmOyA2JthJKhoW8ABYtgCkAxqFTNlKDfC89GUefKNxVsixdMXmXxwGnkEk4NiqMVhwuISV0YW4K0pSCB6oUS7iDvkMcTZFygMb507HYKy3qhKJ+iobJbi+BEPrgGFY2Tq9y5/W31f8Zshp1kCOXpDU6IXEMlEj37ynDaO9Ui/7KI0d+U3xpIT5uUEUtjqBJJamwodimiJoTX8qhFjVv0BhlofwBm76UwwuQNU47c+7jQIOz6fg275yv7nYu6UQUF0gei/CQfl87vVpmtfFEUDPs9uWHkgmuvg+p5FvfLBamdgJg0mte7T1sw5osBrPEf5Z+fjmsr9a4FWrMPfhqgiqS2FUz3WRvA43nT8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
