travis:
  secure:
    BINSTAR_TOKEN: ZX/PxD7YGvovKW9yDXwrM8D/D1maa9tib7XO1j24fAabTDcah9H5rCXg8ZbSFMkbLJhsmh9K4jfDUQ6xAfVzJQo8yqR+RYLtIf1L2+mDgTLgX+wIwvsPuvUkVSCuRNf8wIWuoDAB74ct8D+rl3OXgFN/cEXMIcDabUSoE/6/0lGH1965cTrx9O2j3d7zZEnzsEgu23ivPaO+xCPKpK1s4GUOUpIgzPXFyliVf+JhrIGSz+F6jWsN/xYjMOklIJ+m70ERjiIGblu5yT7ovT7DmGjzwTLNvuqFN4oBMTyH0gKsavbY1G2B1YscFoHMgy2CWOm33elgNQkBjoHBxU2+Zy0+ywhXerekHV/HRDpYz+yrZHZAp+GjLkNtLncKALHWbNCEtkjBYXlmX+Y3A1RY0UtF71zy/D0Hed2feIolaF6oczC/mjigZ1oZp4rsqTIBowRICR1dzaZMexHUVvAnZZjQU//51XVWWmmQmF8nTgNMA7UfnYyFaeI+Pb+jdTeuIJWISoq9nTrfFx1ZOPK0W/TacdlRZQwLVuCuvcwQKu08KMySu6OIFgihsJA/xm95gEEhJLxWTtUhxJFnHTr0cS3zS1aarOjM1Nw22F35tPPHUytABY89SoYUbyNj5os6KjzZhSqY7elwk/1A7pUu/peF3DRAl5MwaXIAYGAlAy4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
